-- query 2

select *
from
	part,
	supplier,
	partsupp,
	nation,
	region
where
	p_partkey = ps_partkey
	and s_suppkey = ps_suppkey
	and p_size = 25
	-- and p_type like '%STEEL'
	and p_type in ('SMALL POLISHED STEEL', 'LARGE ANODIZED STEEL', 'STANDARD PLATED STEEL', 'SMALL ANODIZED STEEL', 'LARGE BRUSHED STEEL', 'LARGE POLISHED STEEL', 'SMALL PLATED STEEL', 'ECONOMY BRUSHED STEEL', 'LARGE PLATED STEEL', 'PROMO BRUSHED STEEL', 'MEDIUM POLISHED STEEL', 'MEDIUM BRUSHED STEEL', 'SMALL BRUSHED STEEL', 'STANDARD BURNISHED STEEL', 'PROMO ANODIZED STEEL', 'MEDIUM PLATED STEEL', 'STANDARD BRUSHED STEEL', 'PROMO PLATED STEEL', 'PROMO POLISHED STEEL', 'STANDARD POLISHED STEEL', 'ECONOMY PLATED STEEL', 'STANDARD ANODIZED STEEL', 'LARGE BURNISHED STEEL', 'PROMO BURNISHED STEEL', 'MEDIUM ANODIZED STEEL', 'ECONOMY BURNISHED STEEL', 'SMALL BURNISHED STEEL', 'ECONOMY ANODIZED STEEL', 'ECONOMY POLISHED STEEL', 'MEDIUM BURNISHED STEEL')
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'EUROPE'
	and ps_supplycost >= 800
;
